config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  constraints(SubdomainPresent) do
    root 'projects#index', as: :subdomain_root
    devise_for :users
    resources :users, only: :index
  end

  # only allow certain routes when there isn't a subdomain
  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
    get '*path' => redirect('/')
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                        exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

  private

  def downcase_subdomain
    self.subdomain = subdomain.try(:downcase)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :registerable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:new, :create]

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch!(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:subdomain, owner_attributes: [:username, :email, :password, :password_confirmation])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :load_schema, :authenticate_user!

  private

  def load_schema
    Apartment::Tenant.switch!('public')
    return unless request.subdomain.present?

    if current_account
      Apartment::Tenant.switch!(current_account.subdomain)
    else
      redirect_to root_url(subdomain: nil)
    end
  end

  def current_account
    @current_account ||= Account.find_by(subdomain: request.subdomain)
  end
  helper_method :current_account

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def flash_messages(opts={})
    @layout_flash = opts.fetch(:layout_flash) { true }

    capture do
      flash.each do |name, msg|
        concat content_tag(:div, msg, id: "flash_#{name}")
      end
    end
  end

  # Trigger to allow displaying errors elsewhere on the page.
  def show_layout_flash?
    @layout_flash.nil? ? true : @layout_flash
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_status(user)
    if current_account.owner == user
      content_tag(:span, '', class: 'glyphicon glyphicon-ok color-success')
    else
      'Invitation Pending'
    end
  end
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default panel-shadow">
  <div class="panel-body">
    <h2>Create an Account...</h2>
    <br>
    <%= simple_form_for @account, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
      <%= f.simple_fields_for :owner do |sub_owner| %>
        <%= f.label :username %>
        <%= sub_owner.text_field :username, required: true, autofocus: true, class: 'form-control' %>
        <br>
        <%= f.label :email %>
        <%= sub_owner.text_field :email, required: true, class: 'form-control' %>
        <br>
        <%= f.label :password %>
        <%= sub_owner.password_field :password, required: true, class: 'form-control', placeholder: 'minimum six characters' %>
        <br>
        <%= f.label :password_confirmation %>
        <%= sub_owner.password_field :password_confirmation, required: true, class: 'form-control' %>
        <br>
      <% end %>
      <%= f.label :subdomain %>
      <div class="input-group">
        <%= f.text_field :subdomain, required: true, placeholder: 'Enter your preferred subdomain', class: 'form-control' %>
        <span class="input-group-addon">timetracker.dev</span>
      </div>
      <br>
      <%= render 'shared/error_messages', object: f.object %>
      <br>
      <%= f.submit class: 'btn btn-primary btn-block', id: 'my-btn' %>
      <br>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="container">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TimeTracker", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <%= flash_messages if show_layout_flash? %>
    <div class="row">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/projects/index.html.erb
<div class="col-md-12">
  <div class="well">
    Hi there! Track your precious time for your awesome project here!
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-title">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li class="secondary-font error-messages"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>Authorized Users</h2>

  <div class="panel panel-default">
    <div class="panel-body">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td class="checkmark"><%= user_status(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="col-md-12">
  <div class="jumbotron hero">
    <div class="frosty">
      <h1>TimeTracker</h1>
      <p>No time like the present to track your projects!</p>
      <p><%= link_to "Create Account", new_account_path, class: 'btn btn-primary btn-lg', id: 'welcome-btn' %></p>
    </div>
  </div>
</div>